### ISSUE TITLE
feat. where u can change the framerate u record in

### ISSUE THREAD

**Issue by W8CODE** [anonfaded/FadCam#23]
you can change from the default 30 fps to 60 or more

**Comment by anonfaded** [comment]
Custom FPS feature, added in `upcoming features` roadmap
https://github.com/anonfaded/FadCam/blob/master/README.md#upcoming-features

**Comment by um6reon** [comment]
> Custom FPS feature, added in `upcoming features` roadmap https://github.com/anonfaded/FadCam/blob/master/README.md#upcoming-features

any plans to have a setting for auto-focus too? would like to disable it

**Comment by anonfaded** [comment]
> > Custom FPS feature, added in `upcoming features` roadmap https://github.com/anonfaded/FadCam/blob/master/README.md#upcoming-features
> 
> any plans to have a setting for auto-focus too? would like to disable it

Can search about it if it can be done then we will do it sure.

**Comment by s0llvan** [comment]
I just finished to develop this functionality, I'm waiting for my pull request to be accepted so I can make a new one with this enhancement

**Comment by s0llvan** [comment]
I just finished to develop this feature, I'm waiting for my preview pull request to be accepted so I can make a new one with this enhancement

**Comment by anonfaded** [comment]
> I just finished to develop this feature, I'm waiting for my preview pull request to be accepted so I can make a new one with this enhancement

Yeah i will merge that soon, thank you for your contribution! 😄

Also are you working on this frame rate feature? If yes then i was thinking to have this feature below the 'quality selection' section on settings fragment. Also to have it synced with all other quality selection features that is saved to saved preferences too.

**Comment by s0llvan** [comment]
You're welcome 🙂

Yes, I have finished a few minutes ago.
Under the selection of the quality of the video actually seems the best place :

![Screenshot_20240916_201712](https://github.com/user-attachments/assets/66015e65-aea8-4ea0-9c0b-a1a984e30876)

**Comment by anonfaded** [comment]
Oh great, I have merged the translations PR and now you can work on this one.
