### ISSUE TITLE
Ability to switch camera options on the main screen

### ISSUE THREAD

**Issue by W8CODE** [anonfaded/FadCam#25]
You will be able to switch between front and back camera right on the main page, instead of having to swipe to settings page, then set it, and then back to main page and record

**Comment by TheImperialOne** [comment]
I can do this, please assign this issue to me

**Comment by anonfaded** [comment]
> I can do this, please assign this issue to me

You can fork the repo and after testing it overall you can open a pull request.

**Comment by Shebyyy** [comment]
Is it possible to add a feature to switch the camera after start recording?

**Comment by anonfaded** [comment]
> Is it possible to add a feature to switch the camera after start recording?

Very likely it is possible, will do it later after other issues are solved.

For now, camera switch button has been added to home page, if you want to try it out, you can check the beta release in releases section.

**Comment by Shebyyy** [comment]
> > Is it possible to add a feature to switch the camera after start recording?
> 
> Very likely it is possible, will do it later after other issues are solved.
> 
> For now, camera switch button has been added to home page, if you want to try it out, you can check the beta release in releases section.

Okay, Thanks 🙏

**Comment by Shebyyy** [comment]
Got it, I'll check everything once again and get back to you.

**Comment by Shebyyy** [comment]
> > > > Is it possible to add a feature to switch the camera after start recording?
> > > 
> > > Very likely it is possible, will do it later after other issues are solved.
> > > 
> > > For now, camera switch button has been added to home page, if you want to try it out, you can check the beta release in releases section.
> > 
> > Yeah I'm using beta one, Thanks 🙏
> 
> Btw can you share feedback for beta version please?
> Like check if the text in widgets is wrapped correctly (previously it was cut from bottom) and also the language changing feature if it works fine.

Got it, I'll check everything once again and get back to you.

**Comment by Shebyyy** [comment]
> > > > Is it possible to add a feature to switch the camera after start recording?
> > > 
> > > Very likely it is possible, will do it later after other issues are solved.
> > > 
> > > For now, camera switch button has been added to home page, if you want to try it out, you can check the beta release in releases section.
> > 
> > Yeah I'm using beta one, Thanks 🙏
> 
> Btw can you share feedback for beta version please?
> Like check if the text in widgets is wrapped correctly (previously it was cut from bottom) and also the language changing feature if it works fine.


it's working fine, all text is wrapped correctly and language changing also working.

**Comment by anonfaded** [comment]
> > > > > Is it possible to add a feature to switch the camera after start recording?
> > > > 
> > > > Very likely it is possible, will do it later after other issues are solved.
> > > > 
> > > > For now, camera switch button has been added to home page, if you want to try it out, you can check the beta release in releases section.
> > > 
> > > Yeah I'm using beta one, Thanks 🙏
> > 
> > Btw can you share feedback for beta version please?
> > Like check if the text in widgets is wrapped correctly (previously it was cut from bottom) and also the language changing feature if it works fine.
> 
> 
> it's working fine, all text is wrapped correctly and language changing also working.
> 

Thank you for testing :)
