### ISSUE TITLE
Recording not saving 

### ISSUE THREAD

**Issue by saltsoftdrink** [anonfaded/FadCam#3]
But where does the recording even show I can not find out

**Comment by anonfaded** [comment]
> But where does the recording even show I can not find out

In your phone's gallery, there will be a folder named as 'FadCam', recordings will be saved there, or you can open the file manager of your phone and there you can find it too in the 'FadCam' directory.

I'll open an issue so i or someone can add better options to have the videos directly in the app. Thank you for using the app 🙂

**Comment by saltsoftdrink** [comment]
> > But where does the recording even show I can not find out
> 
> In your phone's gallery, there will be a folder named as 'FadCam', recordings will be saved there, or you can open the file manager of your phone and there you can find it too in the 'FadCam' directory.
> 
> I'll open an issue so i or someone can add better options to have the videos directly in the app. Thank you for using the app 🙂

No man it's not showing 

Anyways you made a great app

**Comment by anonfaded** [comment]
> > > But where does the recording even show I can not find out
> > 
> > In your phone's gallery, there will be a folder named as 'FadCam', recordings will be saved there, or you can open the file manager of your phone and there you can find it too in the 'FadCam' directory.
> > 
> > I'll open an issue so i or someone can add better options to have the videos directly in the app. Thank you for using the app 🙂
> 
> No man it's not showing 
> 
> Anyways you made a great app

Can you share some details about your phone, the android version and phone model?
Also if you prefer we can discuss on discord or any chat app to better understand the issue.
@anonfaded is my username on discord.

**Comment by saltsoftdrink** [comment]
> > > > But where does the recording even show I can not find out
> > > 
> > > 
> > > In your phone's gallery, there will be a folder named as 'FadCam', recordings will be saved there, or you can open the file manager of your phone and there you can find it too in the 'FadCam' directory.
> > > I'll open an issue so i or someone can add better options to have the videos directly in the app. Thank you for using the app 🙂
> > 
> > 
> > No man it's not showing
> > Anyways you made a great app
> 
> Can you share some details about your phone, the android version and phone model? Also if you prefer we can discuss on discord or any chat app to better understand the issue. @anonfaded is my username on discord.

I don't use discord 

https://ibb.co/5cfMLSJ

**Comment by anonfaded** [comment]
@saltsoftdrink 
The issue is fixed, it was saving the video to `movies` folder, now it saves to `Download` folder. Uninstall the previous app and download the latest fixed version from here: https://github.com/anonfaded/FadCam/releases/tag/v1.0.1
And when the recording is stopped, it can take few seconds to save the video so close the file explorer(`if video isn't there`) and reopen the `Download/FadCam` folder to see the recordings. Letme know if you face any issues : )
For reference, ss of `Android version 14` virtual device:

![Screenshot 2024-07-11 013832](https://github.com/anonfaded/FadCam/assets/124708903/8cfaf845-00cd-477b-af69-87f392d11f98)
