### ISSUE TITLE
[BUG] Just a small UI fix

### ISSUE THREAD

**Issue by derei** [anonfaded/FadCam#32]
### Description
Text clipped in info cards (in date/time too, setting dependent)

### Expected Behavior
Proper text wrapping, font, card size, to maintain a clean UI.

### Screenshots
![Fadcamuifix](https://github.com/user-attachments/assets/162d8b03-9004-497c-900c-bd001de15b84)

### Environment
- **Device:** [Google Pixel 7 Pro]
- **OS:** [GrapheneOS, Android 14]
- **App Version:** [e.g. 1.1.3]

### Priority
- [x] Low
- [ ] Medium
- [ ] High

**Comment by anonfaded** [comment]
Yeah i have fixed that but haven't released yet as I'm adding more features.

But we need to test it, so if you are willing to try the fixed version let me know so i can make a debug release and then you can share feedback.

**Comment by derei** [comment]
@anonfaded yes, of course. I’d be happy to fiddle with it.

**Comment by anonfaded** [comment]
> @anonfaded yes, of course. I’d be happy to fiddle with it.

Beta version is out, please download from the link below and let me know if its better now :)
https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta

**Comment by s0llvan** [comment]
> > @anonfaded yes, of course. I’d be happy to fiddle with it.
> 
> Beta version is out, please download from the link below and let me know if its better now :) https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta

Bug fixed for somes tips on the beta version but not for all :

![20240916_100224](https://github.com/user-attachments/assets/9a2ae751-c9f8-44d0-a88b-b30eb304ae49)

**Comment by anonfaded** [comment]
Hmm i guess it can't be enhanced more at the moment bcz if we do it then on larger screens it will take too much empty space as its not dynamic according to text length. Also i guess your screen is smaller than the standard screen sizes. Cam you share what device you have?

> > > @anonfaded yes, of course. I’d be happy to fiddle with it.
> > 
> > Beta version is out, please download from the link below and let me know if its better now :) https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta
> 
> Bug fixed for somes tips on the beta version but not for all :
> 
> ![20240916_100224](https://github.com/user-attachments/assets/9a2ae751-c9f8-44d0-a88b-b30eb304ae49)
>

**Comment by s0llvan** [comment]
> Hmm i guess it can't be enhanced more at the moment bcz if we do it then on larger screens it will take too much empty space as its not dynamic according to text length. Also i guess your screen is smaller than the standard screen sizes. Cam you share what device you have?
> 
> > > > @anonfaded yes, of course. I’d be happy to fiddle with it.
> > > 
> > > 
> > > Beta version is out, please download from the link below and let me know if its better now :) https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta
> > 
> > 
> > Bug fixed for somes tips on the beta version but not for all :
> > ![20240916_100224](https://private-user-images.githubusercontent.com/178677095/367683316-9a2ae751-c9f8-44d0-a88b-b30eb304ae49.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODUyMjAsIm5iZiI6MTcyNjQ4NDkyMCwicGF0aCI6Ii8xNzg2NzcwOTUvMzY3NjgzMzE2LTlhMmFlNzUxLWM5ZjgtNDRkMC1hODhiLWIzMGViMzA0YWU0OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxMTA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDM2NjNlMzdlMGY5OGE1ODU0OTliMmQyYzE0YWMxMDQ0NzBkY2MxY2Y4YWQ1YWE3MGQxOGE1MjRkYzY2NGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.94pcsbi7BKHffyf6i2YVSXG8a1O5PgP8lUKujJm4rLE)

Galaxy A8 2018 SM-A530F
5,6"
1920x1080

**Comment by anonfaded** [comment]
Okay i have decided to increase the size of widget, when i do it I'll let you know so then you can confirm if it get fixed

> > Hmm i guess it can't be enhanced more at the moment bcz if we do it then on larger screens it will take too much empty space as its not dynamic according to text length. Also i guess your screen is smaller than the standard screen sizes. Cam you share what device you have?
> > 
> > > > > @anonfaded yes, of course. I’d be happy to fiddle with it.
> > > > 
> > > > 
> > > > Beta version is out, please download from the link below and let me know if its better now :) https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta
> > > 
> > > 
> > > Bug fixed for somes tips on the beta version but not for all :
> > > ![20240916_100224](https://private-user-images.githubusercontent.com/178677095/367683316-9a2ae751-c9f8-44d0-a88b-b30eb304ae49.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODUyMjAsIm5iZiI6MTcyNjQ4NDkyMCwicGF0aCI6Ii8xNzg2NzcwOTUvMzY3NjgzMzE2LTlhMmFlNzUxLWM5ZjgtNDRkMC1hODhiLWIzMGViMzA0YWU0OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxMTA4NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDM2NjNlMzdlMGY5OGE1ODU0OTliMmQyYzE0YWMxMDQ0NzBkY2MxY2Y4YWQ1YWE3MGQxOGE1MjRkYzY2NGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.94pcsbi7BKHffyf6i2YVSXG8a1O5PgP8lUKujJm4rLE)
> 
> Galaxy A8 2018 SM-A530F
> 5,6"
> 1920x1080

**Comment by anonfaded** [comment]
@s0llvan I have updated the design of home page, now please check again and letme know if the widgets are fixed.
Download the latest apk from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta

**Comment by s0llvan** [comment]
Thanks, it's fixed for me.

![Screenshot_20240917-173952_FadCam](https://github.com/user-attachments/assets/e5dfe9ff-8da1-4da4-8ea3-09f31728fa63)

**Comment by anonfaded** [comment]
> Thanks, it's fixed for me.
> 
> ![Screenshot_20240917-173952_FadCam](https://github.com/user-attachments/assets/e5dfe9ff-8da1-4da4-8ea3-09f31728fa63)
> 

Your welcome!
I have changed its position and design, and made it to wrap according to text length so now it will push the preview area down if the text needs more space. :)

**Comment by s0llvan** [comment]
@anonfaded is it normal if this fixed has not commited...? (but present in the APK release)

**Comment by anonfaded** [comment]
> @anonfaded is it normal if this fixed has not commited...? (but present in the APK release)

I have committed everything to the master branch, but only the beta version of apk has these new features. I haven't made a release yet as we will do it after i do other features etc

Also are you working on the fps feature to list only the available fps options?

**Comment by s0llvan** [comment]
Oh okay 👍

Yes, i'm working on this, I'm doing the latest tests

**Comment by s0llvan** [comment]
Oh okay 👍

Yes, i'm currently working on this
