### ISSUE TITLE
[FEATURE] The possibilty to set 60 fps in recording

### ISSUE THREAD

**Issue by Tanked4** [anonfaded/FadCam#42]
### Description
Title

### Priority
- [ ] Low
- [☑] Medium
- [ ] High

**Comment by anonfaded** [comment]
Have you tried the beta version which has framerate selection feature?
Download from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.0-beta

**Comment by s0llvan** [comment]
Duplicate of #23
