### ISSUE TITLE
[FEATURE] New icon

### ISSUE THREAD

**Issue by sonalder-darlene** [anonfaded/FadCam#44]
### Description
I've quickly made a more modern icon for your app while keeping some ideas from your original icon. I added a camera as it's a camera app. I've also made one with FADCAM title in it even though I feel it's unnecessary. I'm open to make small changes but it's just a small suggestion without any intention to work on it.
If you know how to make it MaterialYou iconable I could also try to make it so it blends with Android12+ icons and icon colors

### Benefit
I think a more modern icon will make the app more appealing to new users while also make it seems like a more professionnal project that might bring more trust for some users even if I doubt about that last one lol

![FADCAM_logoicon](https://github.com/user-attachments/assets/572f112e-12d6-4efa-94f5-8c552014dd0a)
![FADCAM_logo_text](https://github.com/user-attachments/assets/0c0e3123-49de-4ad2-9519-55bb3d343e9b)

**Comment by sonalder-darlene** [comment]
Thanks, I tried something more minimalist than the original, I also prefer the first one.
To be honest beside maybe resizing the icon and making it MaterialYou compatible I don't feel making much tweaking if you have no other direction to propose.
Well I could try to make one for your other apps in the same minimalist style as this one. I'll try to do one for FADCRYPT and you'll be free to use it how you want.
I'm into privacy so if I could contribute even a tiny bit to your work I would gladly appreciate. But if you want to keep your original too I won't be upset.

**Comment by 888Mouse** [comment]
Hi, I am Korean. I want to work with you Please send me a message on my Telegram @z7777_88

**Comment by anonfaded** [comment]
> Thanks, I tried something more minimalist than the original, I also prefer the first one.
> To be honest beside maybe resizing the icon and making it MaterialYou compatible I don't feel making much tweaking if you have no other direction to propose.
> Well I could try to make one for your other apps in the same minimalist style as this one. I'll try to do one for FADCRYPT and you'll be free to use it how you want.
> I'm into privacy so if I could contribute even a tiny bit to your work I would gladly appreciate. But if you want to keep your original too I won't be upset.

I truly appreciate your help. For FadCam, you can open a pull request and add the high-quality icon in full-size PNG or JPG to the Fastlane folder or anywhere else you prefer. Please note that Android Studio automatically crops icons based on different device versions, so I’ll need the icon without any border radius.

You can also contribute to FadCrypt by designing something attractive with a crypto/lock theme. In the future, more apps will be coming, so if you stay connected, you’ll have the opportunity to contribute to them as well.

By the way, are you skilled in Photoshop? If so, I need help creating better screenshot designs. For example, in the README, you’ll see the current screenshots, but I’d like to have them improved with phone mockups and a more polished overall design. If you're willing to help, let me know, or feel free to ask any questions before starting. I’m planning a major app update in a few days, so I’ll need updated screenshots for that as well.

**Comment by sonalder-darlene** [comment]
I'll do the PR in a few days after having a fresh look on my icon.

I've open an issue on FadCrypt. Well I have somewhat dropped that avatar to replace it with the eyes and spy hat one. Hope you don't mind. But I would be happy to make icons for future apps as well !

I have some skills in Photoshop and would galdly help to make the mockups for your screenshots. I could try to do something with the new screenshots but you'll have to send them. How do you imagine us working together on that ?

**Comment by anonfaded** [comment]
Alright. Right now i have the PSD file in the root of repository which has all the slides with text etc. But the mockup is of double phones, while i want a simple phone mockup(if you can find any mockup similar to what i am using right now of samsung s9) where we can fit one screenshot, and in every slice we can change screenshots in that mockup and will adjust text to describe the features. Also right now the whole design seems very basic so lets see if you can make it better.
I'll provide screenshots and mention all the latest features in a message in some days when I'm done with other issues, then you can do it.
Maybe on discord or here? Whatever seems right to you.

**Comment by sonalder-darlene** [comment]
I've open two PR will try to work on the screenshots mockup ASAP

**Comment by anonfaded** [comment]
> I've open two PR will try to work on the screenshots mockup ASAP

Alright, thanks.
