### ISSUE TITLE
[FEATURE] Add 4K quality option with 5MB bitrate

### ISSUE THREAD

**Issue by tomthenpc** [anonfaded/FadCam#49]
### Description
Please support more standard options

### Benefit
Many device cameras support 4k recording, which is beneficial for actual experience

### Additional Context
none

### Priority
- [ ] Low
- [ ] Medium
- [✔️] High

**Comment by anonfaded** [comment]
We added an fps feature but found that third-party camera apps, including ours, are restricted to 30 fps from the system, even though many devices support 60 fps for their native camera apps.

If you'd like, we can increase the bitrate for 4K recording at 30 fps to improve quality, but please note this will also increase the file size. Let me know if you'd like to proceed with that change and if that can make it slightly better.

**Comment by tomthenpc** [comment]
Thanks for your reply. It would be better if there are more options to choose from, and we can combine them according to the format we want. This is really a great software.

**Comment by anonfaded** [comment]
> Thanks for your reply. It would be better if there are more options to choose from, and we can combine them according to the format we want. This is really a great software.

Thanks for your appreciation and using this app :)

So you want to have a 4k option with increased bitrate right (increased video size and can slightly be better in quality)? Note that due to restrictions from system, fps will remain same (30).

**Comment by tomthenpc** [comment]
> > Thanks for your reply. It would be better if there are more options to choose from, and we can combine them according to the format we want. This is really a great software.
> 
> Thanks for your appreciation and using this app :)
> 
> So you want to have a 4k option with increased bitrate right (increased video size and can slightly be better in quality)? Note that due to restrictions from system, fps will remain same (30).

Yes, I hope the bitrate can be increased. Thanks

**Comment by anonfaded** [comment]
> Yes, I hope the bitrate can be increased. Thanks

Noted. This will be added in the upcoming version of app. First it will be available in beta version and after that in final release.
Also do you have any recommendation on what bitrate you want to have for 4k? Like in video, per second 1.5mb, 2mb, 3mb etc storage space that will be taken etc

**Comment by tomthenpc** [comment]
> > Yes, I hope the bitrate can be increased. Thanks
> 
> Noted. This will be added in the upcoming version of app. First it will be available in beta version and after that in final release. Also do you have any recommendation on what bitrate you want to have for 4k? Like in video, per second 1.5mb, 2mb, 3mb etc storage space that will be taken etc

I used my original camera to record 10 seconds of 1080P and 4K videos (30fps) of the same scene. The bitrate of 1080P is 1Mbps, and that of 4K is 5.8Mbps. The bitrate of Fadcam recording 1080P is acceptable to me, but if it is 4K, I think the bitrate should be increased. The value can be proportionally increased by referring to the bitrate of 1080P.

**Comment by anonfaded** [comment]
> I used my original camera to record 10 seconds of 1080P and 4K videos (30fps) of the same scene. The bitrate of 1080P is 1Mbps, and that of 4K is 5.8Mbps. The bitrate of Fadcam recording 1080P is acceptable to me, but if it is 4K, I think the bitrate should be increased. The value can be proportionally increased by referring to the bitrate of 1080P.

Alright, I think 5MB bitrate is a good option, as we are using HEVC encoder which provides better quality and compression on lower bitrate.
So, a 1-minute video would take 300 MB with this bitrate.

If you want to stay updated about beta-updates, you can join the whatsapp channel or discord. Thanks.
