### ISSUE TITLE
Intent to start recording? 

### ISSUE THREAD

**Issue by vaibhav423** [anonfaded/FadCam#50]
Is there an Intent to start the recording directly.

**Comment by anonfaded** [comment]
Yes, please check this issue, it's already in the list of upcoming-features https://github.com/anonfaded/FadCam/issues/28

**Comment by vaibhav423** [comment]
Oh sorry for the issue then 😅

**Comment by anonfaded** [comment]
> Oh sorry for the issue then 😅

No Problem :)
