### ISSUE TITLE
[BUG] HEVC encoder crashes on LGK40s Phone. TODO: Add H264 selecting option back

### ISSUE THREAD

**Issue by Trackerlist** [anonfaded/FadCam#71]
### Description
As the title says, when I select to start recording, the app just closes.

### Steps to Reproduce
1. Open FadCam
2. On 'Home', click on 'Start'
3. See the app closing by itself

### Expected Behavior
FadCam would start recording afaik.

### Actual Behavior
It doesn't record anything, but crashes instead.

### Environment
- **Device:** LgK40s
- **OS:** Android 10
- **App Version:** 1.2.0

### Additional Context
I download it from F-Droid. I already cleaned all app data, changed the resolution and framerate, removed the watermark, switch between front and back camera, reinstalling it from github, but the crashes still persist. Every time after I start and it crashes, a video file with 0 bytes will appear on 'Records' section as temp_(date and hour).mp4.

### Priority
- [ ] Low
- [ ] Medium
- [X] High (Because there is no way to use the app.)

**Comment by Trackerlist** [comment]
This also happens on beta 1.2.1 btw.

**Comment by anonfaded** [comment]
> I download it from F-Droid.

The version on F-Droid and IzzyOnDroid is outdated and latest version is only on GitHub here in releases. But as you mentioned that still it crashes, this is weird bcz no one have this issue yet. Just as a try, i would suggest to download the beta version from here: https://github.com/anonfaded/FadCam/releases/tag/v1.2.1-beta 

Download the arm64 version and if that still crashes then use the universal version, also let me know when you try this.

**Comment by anonfaded** [comment]
> This also happens on beta 1.2.1 btw.

I think your device doesn't support `HEVC` codec so thats why it crashes. To confirm this please download this older version where we were using the H264 codec for recording so it this works then we got the issue.
https://github.com/anonfaded/FadCam/releases/tag/v1.1.3

Let me know if it works out, so we can fix this in latest version by providing codec choosing option. Thanks

**Comment by Trackerlist** [comment]
That version worked, thanks!

You are right, my device doesn't support HEVC/H.265, so that's why FadCam crashes.

**Comment by anonfaded** [comment]
> That version worked, thanks!
> 
> You are right, my device doesn't support HEVC/H.265, so that's why FadCam crashes.

Alright, thanks for confirming the issue, we will fix this soon! For updates, you can join our discord group too (Optionally)

**Comment by anonfaded** [comment]
@Trackerlist Codec selection feature added, now you can try the latest version from here: https://github.com/anonfaded/FadCam/releases/edit/v1.2.1-beta

**Comment by Trackerlist** [comment]
Worked! I didn't even had to change anything, FadCam itself selected H.264 by default. Thank you for your time!

**Comment by anonfaded** [comment]
> Worked! I didn't even had to change anything, FadCam itself selected H.264 by default. Thank you for your time!

Great! All thanks to @s0llvan 😄
Btw in the codec dropdown, there is h265 visible or only the h264? Curious
