### ISSUE TITLE
[FEATURE] I hope that the function of calling with Tasker can be added

### ISSUE THREAD

**Issue by tch123** [anonfaded/FadCam#75]
### Description
I hope it can be used in conjunction with Tasker. I can use Tasker to directly call and open FadCam.

### Benefit
This can be conveniently and quickly opened according to the set parameters.

### Additional Context
[Tasker App](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm)

**Comment by anonfaded** [comment]
Can you explain why can't it can be done? Is there any issue?

And the app you shared is paid, so i can't test it myself so need complete details about this feature request. Thanks

**Comment by tch123** [comment]
Sorry, I didn't explain it clearly above. In fact, this function is: you can directly open the application and work in the background with one click.

If you do not consider cooperating with third-party applications, this function is to allow the application to create a desktop shortcut and directly perform background recording according to the parameters set in the application after clicking the shortcut, skipping the preview interface.

**Comment by anonfaded** [comment]
> Sorry, I didn't explain it clearly above. In fact, this function is: you can directly open the application and work in the background with one click.
> 
> If you do not consider cooperating with third-party applications, this function is to allow the application to create a desktop shortcut and directly perform background recording according to the parameters set in the application after clicking the shortcut, skipping the preview interface.

Btw we will soon add a widget and long press actions to start recording without opening app, maybe you want something simila. So i guess if you wait for this feature then it will be what you described above.

**Comment by tch123** [comment]
Thank you, this is exactly the functionality I was looking for.
